// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk9iLnVRpy4c6adggn3Le3N5jKgY24Ths',
    appId: '1:1054039258694:android:a63754a6b44dafe55c3c47',
    messagingSenderId: '1054039258694',
    projectId: 'checkpoint6-e87bd',
    storageBucket: 'checkpoint6-e87bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3sud1OehpaBOys7JA_A-wY75mKbdGkcU',
    appId: '1:1054039258694:ios:bd130e66f9294c935c3c47',
    messagingSenderId: '1054039258694',
    projectId: 'checkpoint6-e87bd',
    storageBucket: 'checkpoint6-e87bd.firebasestorage.app',
    iosBundleId: 'br.com.guiengel.geradorDeSenha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx-KAgKBHZ2pufJD8emGLE8t6zY_CnZIg',
    appId: '1:1054039258694:web:574dfa3d77622a695c3c47',
    messagingSenderId: '1054039258694',
    projectId: 'checkpoint6-e87bd',
    authDomain: 'checkpoint6-e87bd.firebaseapp.com',
    storageBucket: 'checkpoint6-e87bd.firebasestorage.app',
  );
}
